import { Header } from '@/src/widgets/header';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

const montserratSans = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratSans.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
